Repository Thomaltarix/My_PGP, pull requests merged in 2024-10, with the labels that each got.

#2 Set up issues templates
  .github/ISSUE_TEMPLATE/feature_request.md
  .gitignore
Labels: documentation

#4 Create the mirroring action file
  .github/workflows/mirror.yml
Labels: enhancement

#9 Parsing w base structure
  .gitignore
  Makefile
  src/help.py
  src/main.py
  src/parse.py
  tests/ciphered
  tests/message
Labels: enhancement

#10 Feat XOR
  src/help.py
  src/main.py
  src/parse.py
  src/utils.py
  src/xor.py
  tests/ciphered
  tests/ciphered_fine
  tests/message
Labels: enhancement

#11 fix(Main): Remove debug print in main
  src/main.py
Labels: enhancement

#13 Feat: RSA
  src/main.py
  src/parse.py
  src/rsa.py
  src/utils.py
  src/xor.py
Labels: enhancement

#22 Feat: Add pgp-xor
  src/main.py
  src/parse.py
  src/pgp_xor.py
Labels: enhancement

#24 Feat: Implement PGP-AES
  src/main.py
  src/parse.py
  src/pgp_aes.py
Labels: enhancement

#26 Fix: PGP-XOR and PGP-AES decryption
  src/main.py
  src/pgp_aes.py
  src/pgp_xor.py
  src/rsa.py
Labels: bug

#27 Fix: Encryption of PGP-AES and PGP-XOR
  src/pgp_aes.py
  src/pgp_xor.py
Labels: bug
